[package]
name = "nes"
version = "0.1.0"
edition = "2021"

[lib]
path = "src/lib.rs"
name = "nes"

[dependencies]

[dev-dependencies]
test-generator = "^0.3"
serde = { version = "1.0.171", features = ["derive"]}
serde_json = "1.0.103"
